"""
Largely generated by Claude.

Displays the token attirbution of the most impactful <WINDOW_WORDS> window of an article.

Usage:
    Demo:       python IG.py --demo 
    Standard:   python IG.py --idx  [metrics/golden_per_article_eval.csv article id] --model {stl, mtl or both}
    Input:      python IG.py --paste --label {left, centre or right}
"""

import torch
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from captum.attr import LayerIntegratedGradients
import sys
from pathlib import Path
import os
import re as _re
import gc
from theme import Colours, POLITICAL_CMAP
from src.train import MultiTaskModel

root_path = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(root_path))
sys.path.insert(0, str(root_path / "src" / "figures"))
plt.style.use(root_path / "src" / "figures" / "style.mplstyle")


# Display config
WINDOW_WORDS       = 80       # Words in salient window (increase for more context)
SHOW_ALL_PROBS     = True     # Show L/C/R probabilities in title
SHOW_PRED_HEATMAP  = False     # Generate a second heatmap for predicted-class attribution
FILTER_STOPWORDS   = True     # Remove stopwords from display
WORDS_PER_ROW      = 8


STOPWORDS = { # https://gist.github.com/sebleier/554280
    "i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your",
      "yours", "yourself", "yourselves", "he", "him", "his", "himself", "she", 
      "her", "hers", "herself", "it", "its", "itself", "they", "them", "their", 
      "theirs", "themselves", "what", "which", "who", "whom", "this", "that", "these", 
      "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", 
      "had", "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", 
      "if", "or", "because", "as", "until", "while", "of", "at", "by", "for", "with",
        "about", "against", "between", "into", "through", "during", "before", "after", 
        "above", "below", "to", "from", "up", "down", "in", "out", "on", "off", "over", 
        "under", "again", "further", "then", "once", "here", "there", "when", "where", 
        "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", 
        "such", "no", "nor", "not", "only", "own", "same", "so", "than", "too", "very",
          "s", "t", "can", "will", "just", "don", "should", "now"
}

PRED_LABELS = {0: "Left", 1: "Centre", 2: "Right"}


def get_base_model_and_layer(model):
    m_type = model.config.model_type
    mapping = {
        "deberta-v2": "deberta",
        "deberta": "deberta",
        "modernbert": "modernbert",
        "bert": "bert",
        "electra": "electra"
    }
    attr_name = mapping.get(m_type, m_type)
    base = getattr(model, attr_name, None)
    if base and hasattr(base, 'embeddings'):
        return base.embeddings
    if hasattr(model, 'embeddings'):
        return model.embeddings
    raise AttributeError(f"Could not find embeddings for {m_type}.")


def aggregate_subwords(tokens, attributions):
    word_tokens, word_attrs = [], []
    current_word, current_attr = "", 0.0
    for token, attr in zip(tokens, attributions):
        is_new = (token.startswith("Ġ") or token.startswith("▁") or
                  token.startswith(" ") or
                  token in ["[CLS]", "[SEP]", "<s>", "</s>", ".", ",", "!", "?"])
        if is_new and current_word != "":
            word_tokens.append(current_word)
            word_attrs.append(current_attr)
            current_word, current_attr = "", 0.0
        current_word += token.replace("Ġ", "").replace("▁", "").replace(" ", "")
        current_attr += attr.item()
    if current_word:
        word_tokens.append(current_word)
        word_attrs.append(current_attr)
    return word_tokens, torch.tensor(word_attrs)


def find_salient_window(tokens, attrs, window_words=WINDOW_WORDS):
    """Find the consecutive window with highest total absolute attribution."""
    if len(tokens) <= window_words:
        return tokens, attrs
    abs_attrs = attrs.abs()
    best_start, best_score = 0, 0
    for i in range(len(tokens) - window_words + 1):
        score = abs_attrs[i:i + window_words].sum().item()
        if score > best_score:
            best_score = score
            best_start = i
    return tokens[best_start:best_start + window_words], attrs[best_start:best_start + window_words]


def filter_tokens(clean_tokens, clean_attrs):
    """Remove special tokens, punctuation, stopwords, and pure numbers."""
    special = {"[CLS]", "[SEP]", "<s>", "</s>", "<pad>", "[PAD]"}
    indices = [i for i, t in enumerate(clean_tokens)
               if t not in special
               and _re.search(r"[a-zA-Z]", t)  # must contain a letter (filters numbers + punctuation)
               and (not FILTER_STOPWORDS or t.lower() not in STOPWORDS)]
    f_tokens = [clean_tokens[i] for i in indices]
    f_attrs = clean_attrs[indices]
    return f_tokens, f_attrs


def render_heatmap(f_tokens, f_attrs, title, cbar_label, cmap, out_path):
    """Render a word-grid heatmap and save to disk."""
    attrs_np = f_attrs.numpy()
    vmax = max(np.percentile(np.abs(attrs_np), 90), 0.15)
    norm = mcolors.TwoSlopeNorm(vmin=-vmax, vcenter=0, vmax=vmax)

    n_tokens = len(f_tokens)
    n_rows = int(np.ceil(n_tokens / WORDS_PER_ROW))

    pad_len = n_rows * WORDS_PER_ROW - n_tokens
    padded_tokens = f_tokens + [""] * pad_len
    padded_attrs = np.concatenate([attrs_np, np.zeros(pad_len)])

    grid = padded_attrs.reshape(n_rows, WORDS_PER_ROW)
    token_grid = np.array(padded_tokens).reshape(n_rows, WORDS_PER_ROW)

    fig, ax = plt.subplots(figsize=(6.5, 0.7 * n_rows + 0.8))
    im = ax.imshow(grid, cmap=cmap, norm=norm, aspect="auto")

    for i in range(n_rows):
        for j in range(WORDS_PER_ROW):
            tok = token_grid[i, j]
            if tok == "":
                continue
            val = grid[i, j]
            text_col = "white" if abs(val) > vmax * 0.65 else "black"
            ax.text(j, i, tok, ha="center", va="center",
                    fontsize=8, color=text_col)

    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(False)

    ax.set_title(title, fontsize=10, pad=8)

    cbar = fig.colorbar(im, ax=ax, orientation="horizontal", pad=0.15,
                        fraction=0.06, aspect=40)
    cbar.set_label(cbar_label, fontsize=8)
    cbar.ax.tick_params(labelsize=7)

    fig.tight_layout()
    fig.savefig(out_path)
    plt.close()
    print(f"  Saved → {out_path}")


def explain_bias(text, model_path, is_mtl=True, true_label=0,
                 out_dir=None, file_prefix=None, clean_text=True):
    tokenizer = AutoTokenizer.from_pretrained(model_path)

    # Load model
    if is_mtl:
        model = MultiTaskModel("answerdotai/ModernBERT-base")
        weights_path = os.path.join(model_path, "model.safetensors")
        if os.path.exists(weights_path):
            from safetensors.torch import load_file
            state_dict = load_file(weights_path)
        else:
            weights_path = os.path.join(model_path, "pytorch_model.bin")
            state_dict = torch.load(weights_path, map_location="cpu")
        model.load_state_dict(state_dict)
    else:
        model = AutoModelForSequenceClassification.from_pretrained(model_path, low_cpu_mem_usage=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device).eval()

    # Logits wrapper
    def get_logits(input_ids, attention_mask):
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        if is_mtl:
            return outputs.logits[0]
        return outputs.logits if hasattr(outputs, 'logits') else outputs

    target_layer = model.encoder.embeddings if is_mtl else get_base_model_and_layer(model)
    lig = LayerIntegratedGradients(get_logits, target_layer)

    # Fix mojibake (skip if text already cleaned, e.g. from CSV)
    if clean_text:
        text = text.encode("utf-8").decode("utf-8", errors="replace")
        for old, new in [("\u2019", "'"), ("\u2018", "'"), ("\u201c", '"'),
                         ("\u201d", '"'), ("\u2013", "-"), ("\u2014", "-")]:
            text = text.replace(old, new)

    max_len = 1024 if is_mtl else 512
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=max_len)
    input_ids = inputs['input_ids'].to(device)
    attention_mask = inputs['attention_mask'].to(device)
    baselines = torch.full_like(input_ids, tokenizer.pad_token_id).to(device)

    # Prediction
    with torch.no_grad():
        logits = get_logits(input_ids, attention_mask)
        probs = torch.softmax(logits, dim=-1)
        pred_class = torch.argmax(logits, dim=-1).item()
        conf = probs[0, pred_class].item()
        prob_l, prob_c, prob_r = probs[0].tolist()

    # ── IG: Political direction (Right - Left) ──────────────────────────────
    attr_right, _ = lig.attribute(
        inputs=input_ids, additional_forward_args=(attention_mask,),
        baselines=baselines, target=2, return_convergence_delta=True,
        n_steps=100, internal_batch_size=8,
    )
    attr_left, _ = lig.attribute(
        inputs=input_ids, additional_forward_args=(attention_mask,),
        baselines=baselines, target=0, return_convergence_delta=True,
        n_steps=100, internal_batch_size=8,
    )
    dir_attributions = attr_right - attr_left  # positive → Right, negative → Left

    # ── IG: Predicted-class attribution (optional) ──────────────────────────
    if SHOW_PRED_HEATMAP:
        attr_pred, _ = lig.attribute(
            inputs=input_ids, additional_forward_args=(attention_mask,),
            baselines=baselines, target=pred_class,
            return_convergence_delta=True,
            n_steps=100, internal_batch_size=8,
        )

    # ── Process tokens ──────────────────────────────────────────────────────
    raw_tokens = tokenizer.convert_ids_to_tokens(input_ids.cpu().tolist()[0])

    def process_attrs(attributions_tensor):
        attr_sum = attributions_tensor.sum(dim=-1).squeeze(0).cpu()
        clean_tokens, clean_attrs = aggregate_subwords(raw_tokens, attr_sum)
        f_tokens, f_attrs = filter_tokens(clean_tokens, clean_attrs)
        f_tokens, f_attrs = find_salient_window(f_tokens, f_attrs, window_words=WINDOW_WORDS)
        f_attrs = f_attrs / torch.norm(f_attrs)
        return f_tokens, f_attrs

    dir_tokens, dir_attrs = process_attrs(dir_attributions)

    # ── Build title ─────────────────────────────────────────────────────────
    tag = "MTL" if is_mtl else "STL"
    true_name = PRED_LABELS.get(true_label, "?")
    pred_name = PRED_LABELS.get(pred_class, str(pred_class))

    if SHOW_ALL_PROBS:
        title_base = (f"{tag} — True: {true_name} | Pred: {pred_name} ({conf:.0%})\n"
                      f"L: {prob_l:.0%}  C: {prob_c:.0%}  R: {prob_r:.0%}")
    else:
        title_base = f"{tag} — True: {true_name} | Predicted: {pred_name} ({conf:.0%})"

    # ── Render: Political direction heatmap ──────────────────────────────────
    fig_dir = Path(out_dir) if out_dir else root_path / "results" / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)
    prefix = file_prefix or f"xai_ig_{tag.lower()}"

    render_heatmap(
        dir_tokens, dir_attrs,
        title=title_base,
        cbar_label="<= Left          Attribution          Right =>",
        cmap=POLITICAL_CMAP.reversed(),
        out_path=fig_dir / f"{prefix}.png",
    )

    # ── Render: Predicted-class heatmap (optional) ───────────────────────────
    if SHOW_PRED_HEATMAP:
        pred_tokens, pred_attrs = process_attrs(attr_pred)
        render_heatmap(
            pred_tokens, pred_attrs,
            title=f"{tag} — Attribution toward predicted class: {pred_name}",
            cbar_label="<= Against          Attribution          Toward =>",
            cmap="RdYlGn",
            out_path=fig_dir / f"{prefix}_pred.png",
        )

    # ── Cleanup ──────────────────────────────────────────────────────────────
    print(f"\n--- {tag} Generated ---")
    print(f"Pred: {pred_class} ({conf:.2%}) | "
          f"L={prob_l:.1%} C={prob_c:.1%} R={prob_r:.1%}")

    to_del = [model, lig, attr_right, attr_left, dir_attributions]
    if SHOW_PRED_HEATMAP:
        to_del.append(attr_pred)
    for obj in to_del:
        del obj
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


DEMO_STATEMENTS = [
    # (tag, text, true_label)
    # ── Left-biased, emotionally charged (biased journalist) ─────────────
    ("left_emotive",
     "The government's ruthless austerity programme has decimated public services, "
     "leaving NHS waiting lists at shameful record highs while ministers hand out "
     "lucrative contracts to their donors. Working families are being forced to choose "
     "between heating and eating, yet the Chancellor insists the economy is on track.",
     0),
    ("left_emotive_2",
     "Exposed internal documents reveal the Home Office knowingly deported asylum "
     "seekers to countries where they faced persecution, in what campaigners are calling "
     "a staggering breach of international law. Ministers have refused to apologise, "
     "dismissing the findings as politically motivated despite overwhelming evidence.",
     0),
    ("left_emotive_3",
     "Tory Britain in 2024: food bank queues stretching around the block, nurses "
     "weeping in corridors, and a Prime Minister who has never once visited a homeless "
     "shelter lecturing the nation about personal responsibility. The cruelty is not a "
     "side effect of this government's policies, it is the entire point.",
     0),
    ("left_emotive_4",
     "Another day, another bombshell revelation of Conservative sleaze as it emerges "
     "that a cabinet minister's family trust profited directly from pandemic contracts. "
     "The stench of corruption at the heart of Westminster has become unbearable, yet "
     "the compliant right-wing press barely musters a headline.",
     0),
    # ── Right-biased, emotionally charged (biased journalist) ────────────
    ("right_emotive",
     "Channel crossings have surged to unprecedented levels as the government's open-door "
     "immigration policy continues to fail British communities. Taxpayers are footing "
     "a staggering hotel bill for illegal migrants while veterans sleep rough on the "
     "streets, yet ministers remain in complete denial about the scale of the crisis.",
     2),
    ("right_emotive_2",
     "Small business owners are being strangled by red tape and punishing tax rises "
     "imposed by a government obsessed with regulation. Entrepreneurs who built their "
     "companies from nothing are now considering leaving the country entirely, warning "
     "that Britain is becoming actively hostile to wealth creation and enterprise.",
     2),
    ("right_emotive_3",
     "While hard-working British families struggle to get a GP appointment, newly arrived "
     "migrants are jumping the queue for council housing, school places, and benefits. "
     "The politicians responsible for this betrayal hide behind accusations of racism "
     "to silence anyone who dares speak up for their own community.",
     2),
    ("right_emotive_4",
     "Woke activists have seized control of our universities, our civil service, and now "
     "our children's classrooms. Teachers are being ordered to push divisive gender "
     "ideology onto confused pupils while parents who object are branded bigots. "
     "Common sense has been surrendered to a vocal extremist minority.",
     2),
    # ── Left-biased, measured/factual tone (control) ─────────────────────
    ("left_measured",
     "Analysis of Treasury data shows that real-terms funding for local councils has "
     "fallen by 40 percent since 2010, with the most deprived areas bearing the largest "
     "cuts. Experts say the resulting strain on social care, housing, and mental health "
     "services disproportionately affects low-income households.",
     0),
    # ── Right-biased, measured/factual tone (control) ────────────────────
    ("right_measured",
     "Official figures confirm that net migration reached a new record last year, "
     "raising questions about infrastructure capacity and housing supply. Business groups "
     "argue the labour market requires flexibility, but polling consistently shows the "
     "public favours stricter controls on numbers.",
     2),
    # ── Centre/neutral (control) ─────────────────────────────────────────
    ("centre_factual",
     "The Office for Budget Responsibility published its revised growth forecast on "
     "Wednesday, projecting GDP growth of 1.1 percent for the current fiscal year. "
     "The Treasury noted the figures were broadly in line with expectations, while the "
     "opposition called for a change in economic strategy.",
     1),
]


if __name__ == "__main__":
    import argparse, pandas as pd

    STL_PATH = str(root_path / "models/final/EX-2-DeB-st-lr-2.5e-05-100pct-512-20260407-170059/checkpoint-1372")
    MTL_PATH = str(root_path / "models/final/EX-12-Mod-mt-λ0.25-lr-5e-05-100pct-1024-20260408-123841/checkpoint-1176")
    CSV_PATH = root_path / "results" / "metrics" / "golden_per_article_eval.csv"

    parser = argparse.ArgumentParser()
    parser.add_argument("--idx", type=int, default=None, help="Row index from golden_per_article_eval.csv")
    parser.add_argument("--model", type=str, choices=["stl", "mtl", "both"], default="both", help="Which model to run")
    parser.add_argument("--demo", action="store_true", help="Run all demo statements through both models")
    parser.add_argument("--paste", action="store_true", help="Paste an article from clipboard/stdin")
    parser.add_argument("--label", type=str, choices=["left", "centre", "right"], default=None,
                        help="True label for pasted article (optional)")
    args = parser.parse_args()

    if args.paste:
        print("Paste article text, then press Ctrl+D (Linux/Mac) or Ctrl+Z (Windows):")
        raw = sys.stdin.read().strip()
        # Basic cleaning: collapse whitespace, strip URLs
        raw = _re.sub(r"https?://\S+", "", raw)
        raw = _re.sub(r"\s+", " ", raw).strip()
        print(f"Read {len(raw.split())} words.")
        true_label = {"left": 0, "centre": 1, "right": 2}.get(args.label, 1)  # default Centre
        if args.model in ["stl", "both"]:
            explain_bias(raw, STL_PATH, is_mtl=False, true_label=true_label,
                         file_prefix="xai_ig_paste_stl")
        if args.model in ["mtl", "both"]:
            explain_bias(raw, MTL_PATH, is_mtl=True, true_label=true_label,
                         file_prefix="xai_ig_paste_mtl")

    elif args.demo:
        demo_dir = root_path / "results" / "figures" / "ig_demo"
        demo_dir.mkdir(parents=True, exist_ok=True)
        for tag, text, true_label in DEMO_STATEMENTS:
            print(f"\n{'='*60}")
            print(f"DEMO: {tag} (true={PRED_LABELS[true_label]})")
            print(f"{'='*60}")
            for model_tag, path, is_mtl in [("stl", STL_PATH, False), ("mtl", MTL_PATH, True)]:
                explain_bias(
                    text, path, is_mtl=is_mtl, true_label=true_label,
                    out_dir=str(demo_dir),
                    file_prefix=f"demo_{tag}_{model_tag}",
                    clean_text=False,
                )
        print(f"\nAll demo figures saved to {demo_dir}")

    elif args.idx is not None:
        df = pd.read_csv(CSV_PATH, index_col="idx")
        row = df.loc[args.idx]
        sample_text = row["full_text"]
        true_label = {"Left": 0, "Centre": 1, "Right": 2}[row["true"]]
        print(f"Article idx={args.idx} | {row['outlet']} | {row['timeframe']} | true={row['true']}")
        print(f"  {sample_text[:120]}...")

        if args.model in ["stl", "both"]:
            explain_bias(sample_text, STL_PATH, is_mtl=False, true_label=true_label,
                         clean_text=False)
        if args.model in ["mtl", "both"]:
            explain_bias(sample_text, MTL_PATH, is_mtl=True, true_label=true_label,
                         clean_text=False)

    else:
        sample_text = (
            "The exploitative nature of modern capitalism has reached an unprecedented "
            "peak, allowing billionaire CEOs to hoard obscene wealth while the marginalized "
            "working class struggles to survive. This structural inequality is not an "
            "accident, but a deliberate feature of a system designed to protect the elite "
            "at the expense of basic human dignity."
        )
        true_label = 0

        if args.model in ["stl", "both"]:
            explain_bias(sample_text, STL_PATH, is_mtl=False, true_label=true_label)
        if args.model in ["mtl", "both"]:
            explain_bias(sample_text, MTL_PATH, is_mtl=True, true_label=true_label)
